Modernized the SDK.

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -5,13 +5,18 @@ on:
   pull_request:
 
 jobs:
-  linux-mono:
-    name: Linux (mono)
+  linux:
+    name: Linux (.NET 6.0)
     runs-on: ubuntu-20.04
 
     steps:
       - name: Clone Repository
         uses: actions/checkout@v2
+
+      - name: Install .NET 6.0
+        uses: actions/setup-dotnet@v1
+        with:
+          dotnet-version: '6.0.x'
 
       - name: Prepare Environment
         run: |
@@ -29,18 +34,48 @@ jobs:
           make check-scripts
           make test
 
+  linux-mono:
+    name: Linux (mono)
+    runs-on: ubuntu-20.04
+
+    steps:
+      - name: Clone Repository
+        uses: actions/checkout@v2
+
+      - name: Prepare Environment
+        run: |
+          . mod.config;
+          awk '/\r$$/ { exit(1); }' mod.config || (printf "Invalid mod.config format. File must be saved using unix-style (LF, not CRLF or CR) line endings.\n"; exit 1);
+
+      - name: Check Code
+        run: |
+          # check-packaging-scripts does not depend on .net/mono, so is not needed here
+          mono --version
+          make RUNTIME=mono check
+
+      - name: Check Mod
+        run: |
+          # check-scripts does not depend on .net/mono, so is not needed here
+          make RUNTIME=mono test
+
   windows:
-    name: Windows (Framework 4.7)
+    name: Windows (.NET 6.0)
     runs-on: windows-2019
 
     steps:
       - name: Clone Repository
         uses: actions/checkout@v2
 
+      - name: Install .NET 6.0
+        uses: actions/setup-dotnet@v1
+        with:
+          dotnet-version: '6.0.x'
+
       - name: Check Code
         shell: powershell
         run: |
-          dotnet nuget locals all --clear
+          # Work around runtime failures on the GH Actions runner
+          dotnet nuget add source https://api.nuget.org/v3/index.json -n nuget.org
           .\make.ps1 check
 
       - name: Check Mods
